# Generated by Django 5.2.11 on 2026-03-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('company_user', 'Company User')], max_length=20, null=True),
        ),
    ]
