# Generated by Django 5.2.11 on 2026-03-01 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('companies', '0004_company_evaluation_window_minutes_and_more'),
        ('signals', '0005_alter_signal_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerthistory',
            old_name='acknowledged_at',
            new_name='acked_at',
        ),
        migrations.RenameField(
            model_name='alerthistory',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='alerthistory',
            name='is_acknowledged',
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('acked', 'Acknowledged')], default='sent', max_length=10),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='channel',
            field=models.CharField(default='telegram', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_histories', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='message',
            field=models.TextField(help_text='Rendered alert message'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_histories', to='signals.signal'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High')], max_length=20),
        ),
    ]
