# Generated by Django 5.2.11 on 2026-03-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_acknowledged_at_alerthistory_acked_at_and_more'),
        ('companies', '0005_company_telegram_chat_id'),
        ('incidents', '0003_incident_telegram_notified'),
        ('signals', '0007_signal_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerthistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_histories', to='incidents.incident'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('slack', 'Slack')], default='telegram', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_histories', to='signals.signal'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('warning', 'Warning')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='alertrule',
            unique_together={('company', 'severity')},
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['company', 'status'], name='alerts_aler_company_9bed60_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['channel', 'status'], name='alerts_aler_channel_e7f437_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['company', 'severity'], name='alerts_aler_company_abdc35_idx'),
        ),
    ]
