# Generated by Django 5.2.11 on 2026-03-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alerthistory_options_alerthistory_incident_and_more'),
        ('incidents', '0003_incident_telegram_notified'),
        ('signals', '0007_signal_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistory',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_histories', to='incidents.incident'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_histories', to='signals.signal'),
        ),
    ]
