# Generated by Django 5.2.11 on 2026-03-02 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alerthistory_incident_and_more'),
        ('companies', '0005_company_telegram_chat_id'),
        ('incidents', '0003_incident_telegram_notified'),
        ('signals', '0007_signal_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistory',
            name='message',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['incident'], name='alerts_aler_inciden_3bac0b_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['signal'], name='alerts_aler_signal__37838a_idx'),
        ),
    ]
