# Generated by Django 5.2.11 on 2026-03-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alerthistory_message_and_more'),
        ('companies', '0006_companymembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertrule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='alertrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='duration',
            field=models.IntegerField(default=0, help_text='Seconds metric must stay above threshold'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='metric',
            field=models.CharField(choices=[('cpu', 'CPU'), ('ram', 'RAM'), ('disk', 'Disk')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertrule',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertrule',
            name='operator',
            field=models.CharField(choices=[('>', 'Greater than'), ('<', 'Less than')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertrule',
            name='threshold',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['company', 'metric'], name='alerts_aler_company_0b301a_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['metric', 'is_active'], name='alerts_aler_metric_95f7a2_idx'),
        ),
    ]
