# Generated by Django 6.0.2 on 2026-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(help_text='Employee count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
