# Generated by Django 5.2.11 on 2026-03-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_evaluation_window_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram user or group chat_id for alerts', null=True),
        ),
    ]
