# Generated by Django 5.2.11 on 2026-03-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_telegram_chat_id'),
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infraagent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='infraagent',
            name='api_key',
            field=models.CharField(editable=False, help_text='Auto-generated secure API key for agent authentication', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='infraagent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable agent without deleting it'),
        ),
        migrations.AlterField(
            model_name='infraagent',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Last successful heartbeat timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='infraagent',
            name='name',
            field=models.CharField(help_text='Human-readable agent name (e.g. prod-web-1, local-dev)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='infraagent',
            index=models.Index(fields=['api_key'], name='infra_infra_api_key_31144d_idx'),
        ),
        migrations.AddIndex(
            model_name='infraagent',
            index=models.Index(fields=['company', 'is_active'], name='infra_infra_company_3db276_idx'),
        ),
    ]
