# Generated by Django 5.2.11 on 2026-03-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companymembership'),
        ('infra', '0002_alter_infraagent_options_alter_infraagent_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraMetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('cpu', 'CPU'), ('ram', 'RAM'), ('disk', 'Disk')], db_index=True, max_length=20)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_history', to='companies.company')),
                ('infra_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_history', to='infra.infraagent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['infra_agent', 'metric', 'created_at'], name='infra_infra_infra_a_8f2bea_idx'), models.Index(fields=['company', 'metric', 'created_at'], name='infra_infra_company_f94f4a_idx')],
            },
        ),
    ]
