# Generated by Django 5.2.11 on 2026-02-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_alter_signal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
