# Generated by Django 5.2.11 on 2026-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_alter_signal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='detected_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='predicted_impact',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='signal_type',
        ),
        migrations.AddField(
            model_name='signal',
            name='downtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='error_rate_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='response_time_ms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signal',
            name='risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='signal',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
    ]
