# Generated by Django 5.2.11 on 2026-03-01 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_evaluation_window_minutes_and_more'),
        ('signals', '0004_rename_detected_at_signal_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='companies.company'),
        ),
    ]
