# Generated by Django 5.2.11 on 2026-03-02 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_alter_infraagent_options_alter_infraagent_api_key_and_more'),
        ('signals', '0005_alter_signal_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='infra_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='infra.infraagent'),
        ),
        migrations.AddField(
            model_name='signal',
            name='metric',
            field=models.CharField(blank=True, help_text='cpu | ram | disk', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='metric_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('infra', 'Infrastructure'), ('sla', 'SLA')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='signal',
            name='response_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('warning', 'Warning'), ('critical', 'Critical')], default='low', max_length=10),
        ),
    ]
