# Generated by Django 5.2.11 on 2026-03-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('signals', '0006_signal_infra_agent_signal_metric_signal_metric_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='incidents.incident'),
        ),
    ]
