# Generated by Django 5.2.11 on 2026-03-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companymembership'),
        ('incidents', '0005_incident_escalation_level_incident_last_escalated_at_and_more'),
        ('infra', '0003_inframetrichistory'),
        ('signals', '0007_signal_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['company', 'metric'], name='signals_sig_company_6b6c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['company', 'status'], name='signals_sig_company_059aec_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['metric', 'severity'], name='signals_sig_metric_26b592_idx'),
        ),
    ]
