# Generated by Django 5.2.11 on 2026-03-02 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_telegram_chat_id'),
        ('incidents', '0001_initial'),
        ('infra', '0002_alter_infraagent_options_alter_infraagent_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('assignment', 'Assignment'), ('note', 'Note')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-opened_at']},
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['company', 'status'], name='incidents_i_company_caa603_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['infra_agent', 'status'], name='incidents_i_infra_a_ef3e41_idx'),
        ),
        migrations.AddField(
            model_name='incidenttimeline',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='incidents.incident'),
        ),
        migrations.AddIndex(
            model_name='incidenttimeline',
            index=models.Index(fields=['incident', 'event_type'], name='incidents_i_inciden_1f04ff_idx'),
        ),
    ]
