# Generated by Django 5.2.11 on 2026-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidenttimeline_alter_incident_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='telegram_notified',
            field=models.BooleanField(default=False),
        ),
    ]
