# Generated by Django 5.2.11 on 2026-03-03 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companymembership'),
        ('incidents', '0003_incident_telegram_notified'),
        ('infra', '0002_alter_infraagent_options_alter_infraagent_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['company', 'acknowledged_at'], name='incidents_i_company_e04321_idx'),
        ),
    ]
