# Generated by Django 5.2.11 on 2026-03-03 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companymembership'),
        ('incidents', '0004_incident_acknowledged_at_incident_acknowledged_by_and_more'),
        ('infra', '0003_inframetrichistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='escalation_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['company', 'escalation_level'], name='incidents_i_company_ab0122_idx'),
        ),
    ]
