# Generated by Django 5.2.11 on 2026-03-13 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companymembership'),
        ('incidents', '0005_incident_escalation_level_incident_last_escalated_at_and_more'),
        ('infra', '0003_inframetrichistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='warning', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='title',
            field=models.CharField(default='Infrastructure Incident', max_length=255),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['company', 'severity'], name='incidents_i_company_048421_idx'),
        ),
    ]
