# Generated by Django 5.2.11 on 2026-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('signal_id', models.IntegerField()),
                ('severity', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook')], max_length=20)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['signal_id'], name='notificatio_signal__f4a710_idx')],
            },
        ),
    ]
